spring:
    datasource:
      url: jdbc:mysql://111.231.72.98:3306/mlytest
      username: root
      password: Root-123456
      driver-class-name: com.mysql.jdbc.Driver
    mvc:
      view:
        prefix: /WEB-INF/jsp/
        suffix: .jsp

server:
  port: 8080
  context-path: /

mybatis:
  typeAliasesPackage: com.example.demo.entity
  mapperLocations: classpath:mapper/*.xml
